# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleDFR',
            fields=[
            ],
        ),
    ]
